### ISSUE TITLE
NetCDF output

### ISSUE THREAD

**Issue by sandreza** [CliMA/LESbrary.jl#134]
We use julia, but if we want other people to easily parse and analyze the data generated by Oceananigans we should use NetCDF. This includes collaborators that have scripts that already read in NetCDF files and analyze the resulting data

**Comment by glwagner** [comment]
We include an option for creating `NetCDF` output writers in `three_layer_constant_fluxes_simulation`:

https://github.com/CliMA/LESbrary.jl/blob/9275cd3937cfedf2466af599cf08c9e319dd55d0/src/IdealizedExperiments/three_layer_constant_fluxes.jl#L377-L419

Is this feature what the issue is referring to? If it is then we support it for the only LESbrary setup we provide, so I think we can close this.

We don't really distribute data now (since we are actively developing the setups, eg #131) so I don't think this is something to consider yet.

**Comment by sandreza** [comment]
With the mesoscale simulations I'll want to start distributing them, but you're right that the feature is implemented! I'll do a quick test and then close the issue

**Comment by glwagner** [comment]
In that case this is an Oceananigans issue not LESbrary (eg do we support NetCDF?)

**Comment by sandreza** [comment]
Looks like it works! And @glwagner , agreed :)
